config/routes.rb
Rails.application.routes.draw do
  resources :groups, only: [:index, :show, :new, :create, :update]
  resources :transactions, only: [:index, :new, :create]
  resources :users, only: [:new, :create]
  root "sessions#welcome"
  get 'login', to: 'sessions#new'   
  post 'login', to: 'sessions#create'   
  get 'welcome', to: 'sessions#welcome'
  get 'sign_out' => 'sessions#destroy'
  get 'external_index', to: 'transactions#external_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  belongs_to :user
  # has_and_belongs_to_many :transactions
  has_and_belongs_to_many :deals, foreign_key: 'group_id', class_name: 'Transaction'
  has_one_attached :image
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true
  belongs_to :user
  has_and_belongs_to_many :groups
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  has_many :transactions
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def require_login
    return true if logged_in?

    redirect_to welcome_path, notice: 'You must be logged in to access this section!'
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :require_login

  # GET /groups or /groups.json
  def index
    @groups = Group.all.order(name: :asc)
  end

  # GET /groups/1 or /groups/1.json
  def show
    @groupdeals = @group.deals
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    selected_id = params[:group][:other_transaction_ids]
    transaction = Transaction.find(selected_id)
    group = Group.find(params[:id])
    group.deals << transaction
    redirect_to group_path(group)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(name: params[:name])
    if @user
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/welcome'
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  before_action :require_login

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
    @owntransactions = Transaction.where(user: current_user).order(date: :desc)
  end

  def external_index
    @owntransactions = Transaction.where(user: current_user).order(date: :desc)
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @groups = Group.all
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params.merge(user_id: current_user.id))
    @transaction.groups << Group.where(id: params[:transaction][:group_ids])
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amount, :date, :group_ids)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      redirect_to new_user_path
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_transaction_sum
    sum = 0
    @group.deals.each do |deal|
      sum += deal.amount
    end
    eurofy(sum)
  end

  def group_transaction_count
    @group.deals.count
  end

  def check_if_other_group
    @otherdeals = []
    Transaction.all.each do |trans|
      @otherdeals << trans unless @groupdeals.ids.include?(trans.id)
    end
    @otherdeals
  end

  def attached?(obj)
    if obj.image.attached?
      render partial: 'single-image'
    else
      render partial: 'no-image'
    end
  end

  def index_attached?(obj)
    if obj.image.attached?
      render partial: 'index-single-image', locals: {group: obj}
    else
      render partial: 'no-image'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in_render
    if logged_in?
      render 'sessions/logged_in'
    else
      render 'sessions/logged_out'
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def total_transaction_sum
    sum = 0
    @owntransactions.each do |transaction|
      sum += transaction.amount
    end
    sum
  end

  def total_external_transaction_sum
    sum = 0
    @owntransactions.each do |transaction|
      sum += transaction.amount if transaction.groups.empty?
    end
    sum
  end

  def eurofy(amount)
    if amount < 10
      amount.to_s.insert(0, '0,0').insert(-1, '€')
    elsif amount < 100
      amount.to_s.insert(0, '0,').insert(-1, '€')
    else
      amount.to_s.insert(-3, ',').insert(-1, '€')
    end
  end

  def no_groups?(trans)
    if trans.groups.empty?
      render partial: 'single-transactions', locals: {transaction: trans}
    end
  end

  def trans_img_attached?(trans)
    if trans.groups.first and trans.groups.first.image.attached?
      render partial: 'single-image', locals: {transaction: trans}
    else
      render partial: 'groups/no-image'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<div class="main-page form-main-page bg-grey">
<%= form_with(model: group, local: true) do |form| %>
  <div class="form-main-content">
    <div class="field mb-0">
      <%= form.text_field :name, placeholder: 'Name', class: 'form-field border-0' %>
    </div>
    <div class="w-100 d-flex justify-content-center">
      <div class="line"></div>
    </div>
    <div class="field image-field bg-white grey mb-0">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
    <div class="actions footer mb-0">
      <button type="submit" class="submit-button-fuck-you text-white rounded w-100 h-100">Create Group</button>
    </div>
  </div>
</div>
<% end %>

app/views/groups/_index-single-image.html.erb
<%= image_tag url_for(group.image), class: 'group-show-icon' %>

app/views/groups/_main-page.html.erb
<div class="main-page group-main-page bg-grey">
  <div class="trans-container">
    <% @groups.each do |group| %>
      <%= link_to group, :action => 'go' do %>
      <div class="single-trans-container bg-white grey d-flex">
        <%= index_attached?(group) %>
        <div class="single-trans-container-info d-flex flex-column justify-content-between w-100">
          <div class="single-trans-container-info-up d-flex justify-content-between">
            <div class="trans-name"><%= group.name %></div>
            <div class="trans-amount"></div>
          </div>
          <div class="single-trans-container-info-down">
            <div class="trans-date"><%= group.created_at.to_date %></div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/groups/_no-image.html.erb
<img class="group-show-icon" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Solid_white.svg/768px-Solid_white.svg.png" alt="">

app/views/groups/_single-image.html.erb
<%= image_tag url_for(@group.image), class: 'group-show-icon' %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="header">
  <%= render 'layouts/nav' %>

  <h2 class="nav-header">Groups</h2>

  <div class="border w-100"></div>
</div>

<%= render 'main-page' %>

<%= link_to new_group_path, :action => 'go' do %>
<div class="footer d-flex justify-content-center align-items-center">
  <p class="small-footer d-flex justify-content-center align-items-center text-white rounded w-100 h-100">New Group</p>
</div>
<% end %>

app/views/groups/new.html.erb
<div class="header">
  <%= render 'layouts/nav' %>
  <h2 class="nav-header">New Group</h2>
  <div class="border w-100"></div>
</div>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="header group-header">
  <%= render 'layouts/nav' %>
  <h2 class="nav-header">Group</h2>
  <div class="group-show-header d-flex justify-content-start align-items-between">
    <div class="group-show-header-img">
      <%= attached?(@group) %>
    </div>
    <div class="group-show-header-right d-flex flex-column align-items-end w-100">
      <div class="group-show-header-name grey">
        <%= @group.name %>
      </div>
      <div class="group-show-header-info">
        <p class="group-show-header-info-field grey mt-2 mb-4"> 
          Total Sum: <span><%= group_transaction_sum %></div></span>
        </p>
        <p class="group-show-header-info-field grey mb-0"> 
          Total Transactions: <span><%= group_transaction_count %></div></span>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="main-page single-group-main-page bg-grey">
  <div class="trans-container">
    <% @group.deals.each do |deal| %>
      <div class="single-trans-container bg-white grey d-flex">
        <div class="single-trans-container-info d-flex flex-column justify-content-between w-100">
          <div class="single-trans-container-info-up d-flex justify-content-between">
            <div class="trans-name"><%= deal.name %></div>
          </div>
          <div class="single-trans-container-info-down">
            <div class="trans-date"><%= deal.user.name %></div>
          </div>
        </div>
        <div class="trans-name"><%= eurofy(deal.amount) %></div>
      </div>  
    <% end %>
      <div class="single-trans-container form-container bg-white grey d-flex">
        <div class="single-trans-container-info d-flex flex-column justify-content-between w-100">
          <%= form_with(model: @group, local: true) do |form| %>
            <%= form.select :other_transaction_ids, check_if_other_group.map{|transc| [transc.name, transc.id]}, {}, class: 'group-field border-0 text-center w-100' %>
            <div class="actions footer mb-0">
                   <button type="submit" class="submit-button-fuck-you text-white rounded w-100 h-100">Submit</button>
            </div>
          <% end %>
        </div>
      </div>  
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar startpage d-flex justify-content-between align-items-start px-5 pt-5">
  <%= link_to 'E-DEALS', welcome_path, class: "link nav-element text-white text-decoration-none" %>
  <%= link_to "Sign Out", sign_out_path, class: " link nav-element text-white text-decoration-none" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;700&display=swap');
  </style> 
  <script
      src="https://kit.fontawesome.com/9a2f12287f.js"
      crossorigin="anonymous"
    ></script>
  <head>
    <title>E-DEALS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
			  src="https://code.jquery.com/jquery-3.6.0.min.js"
			  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			  crossorigin="anonymous"></script>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/transactions/_ext-main-page.html.erb
<div class="main-page bg-grey">
  <div class="trans-container">
    <% @owntransactions.each do |transaction| %>
      <%= no_groups?(transaction) %>
    <% end %>
  </div>
</div>

app/views/transactions/_form.html.erb
<div class="main-page form-main-page bg-grey">
  <%= form_with(model: transaction, local: true) do |form| %>

  <div class="form-main-content">
    <div class="field mb-0">
      <%= form.text_field :name, placeholder: 'Name', class: 'form-field border-0' %>
    </div>
    <div class="w-100 d-flex justify-content-center">
      <div class="line"></div>
    </div>
    <div class="field mb-0">
      <%= form.number_field :amount, placeholder: 'Amount in Cents', class: 'form-field border-0' %>
    </div>
    <div class="w-100 d-flex justify-content-center">
      <div class="line"></div>
    </div>
    <div class="field datefield d-flex justify-content-center bg-white mb-0">
      <%= form.date_select :date %>
    </div>
    <div class="w-100 d-flex justify-content-center">
      <div class="line"></div>
    </div>
    <div class="field mb-0 group-field-container d-flex justify-content-center bg-white">
      <%= form.select :group_ids, Group.all.map{|x| [x.name,x.id]}, {}, multiple: true, class: 'group-field border-0 text-center' %>
    </div>
    <div class="actions footer mb-0">
      <button type="submit" class="submit-button-fuck-you text-white rounded w-100 h-100">Create Transaction</button>
    </div>
  </div>

</div>

  
<% end %>

app/views/transactions/_main-page.html.erb
<div class="main-page bg-grey">
  <div class="trans-container">
    <% @owntransactions.each do |transaction| %>
      <div class="single-trans-container bg-white grey d-flex">
        <%= trans_img_attached?(transaction) %>
        <div class="single-trans-container-info d-flex flex-column justify-content-between w-100">
          <div class="single-trans-container-info-up d-flex justify-content-between">
            <div class="trans-name"><%= transaction.name %></div>
            <div class="trans-amount"><%= eurofy(transaction.amount) %></div>
          </div>
          <div class="single-trans-container-info-down">
            <div class="trans-date"><%= transaction.date %></div>
          </div>
        </div>
      </div>  
    <% end %>
  </div>
</div>

app/views/transactions/_single-image.html.erb
<%= image_tag url_for(transaction.groups.first.image), class: 'icon' %>

app/views/transactions/_single-transactions.html.erb
<div class="single-trans-container bg-white grey d-flex">
  <img class="icon" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Solid_white.svg/768px-Solid_white.svg.png" alt="">
  <div class="single-trans-container-info d-flex flex-column justify-content-between w-100">
      <div class="single-trans-container-info-up d-flex justify-content-between">
      <div class="trans-name"><%= transaction.name %></div>
      <div class="trans-amount"><%= eurofy(transaction.amount) %></div>
      </div>
      <div class="single-trans-container-info-down">
      <div class="trans-date"><%= transaction.date %></div>
      </div>
  </div>
</div>  

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/external_index.html.erb
<div class="header">
  <%= render 'layouts/nav' %>

  <h2 class="nav-header">Ext. Transactions</h2>

  <div class="transaction-sum-section d-flex justify-content-between align-items-center grey bg-white px-5">
    <p class="total-sum">Total Sum:</p>
    <div class="total-sum-amount"><%= eurofy(total_external_transaction_sum) %></div>
  </div>
  <div class="border w-100"></div>
</div>

<%= render 'ext-main-page'%>

<%= link_to new_transaction_path, :action => 'go' do %>
<div class="footer d-flex justify-content-center align-items-center">
  <p class="small-footer d-flex justify-content-center align-items-center text-white rounded w-100 h-100">New Transaction</p>
</div>
<% end %>

app/views/transactions/index.html.erb
<div class="header">
  <%= render 'layouts/nav' %>

  <h2 class="nav-header">Transactions</h2>

  <div class="transaction-sum-section d-flex justify-content-between align-items-center grey px-5">
    <p class="total-sum">Total Sum:</p>
    <div class="total-sum-amount"><%= eurofy(total_transaction_sum) %></div>
  </div>
  <div class="border w-100"></div>
</div>

<%= render 'main-page' %>

<%= link_to new_transaction_path, :action => 'go' do %>
<div class="footer d-flex justify-content-center align-items-center">
  <p class="small-footer d-flex justify-content-center align-items-center text-white rounded w-100 h-100">New Transaction</p>
</div>
<% end %>

app/views/transactions/new.html.erb
<div class="header">
  <%= render 'layouts/nav' %>
  <h2 class="nav-header">New Transaction</h2>
  <div class="border w-100"></div>
</div>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @transaction.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>
<td><%= link_to 'Destroy', @transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="startpage">
      <%= form_for @user, :html => {:class => 'd-flex flex-column align-items-center'} do |f|%>  
      <%= f.label :name, nil, class: 'text-field-label' %><br>  
      <%= f.text_field :name, class: 'text-field rounded-pill mb-5' %><br>   
      <%= f.submit 'Sign Up', class: 'welcome-buttons rounded-pill' %>
    <%end%>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>